apiVersion: apps/v1
kind: Deployment
metadata:
  name: vregistration-statistics-api-deployment
  labels:
    app: vregistration-statistics-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vregistration-statistics-api
  template:
    metadata:
      labels:
        app: vregistration-statistics-api
    spec:
      containers:
      - name: vregistration-statistics
        image: 051786297280.dkr.ecr.us-east-2.amazonaws.com/vregistration-statistics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
