apiVersion: apps/v1
kind: Deployment
metadata:
  name: vregistration-statistics-api-deployment
  labels:
    app: vregistration-statistics-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vregistration-statistics-api
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vregistration-statistics-api
        role: rolling-update
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: vregistration-statistics
        image: 051786297280.dkr.ecr.us-east-2.amazonaws.com/vregistration-statistics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
