apiVersion: v1
kind: Service
metadata:
  name: vregistration-statistics-api-service
spec:
  selector:
    app: vregistration-statistics-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
