on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.DOCKER__HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"

    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag vrsc_test/v1

    - name: Tag the Docker Image
      run: docker tag vrsc_test/v1 supathth1919/vregstats

    - name: Push the Docker Image
      run: docker push supathth1919/vregstats
